### ISSUE TITLE
PostgreSQL table names are not quoted in object browser

### ISSUE THREAD

**Issue by rgordill** [squirrel-sql-client/squirrel-sql-code#36]
PostgreSQL defaults to lowercase when table name is not quoted. in 4.7.1, columns are quoted but tables not:

Example, using object browser for data for the table `uData`, an exception is raised in the UI:

```
Error occurred during task execution: | java.lang.IllegalStateException: Failed any way to execute content SQL. See former warning log entries for details.
```

Looking into the logs:

```
2024-07-15 08:49:06:521 [pool-1-thread-1] WARN  net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.table.ContentsTab  - Failed to execute content SQL: select tbl."VM",tbl."Powerstate" from public.uData tbl
org.postgresql.util.PSQLException: ERROR: relation "public.udata" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
        at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.table.ContentsTab.createResultSet(ContentsTab.java:352)
        at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.table.ContentsTab.createDataSet(ContentsTab.java:251)
        at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.BaseDataSetTab.lambda$refreshComponent$0(BaseDataSetTab.java:127)
        at net.sourceforge.squirrel_sql.fw.util.TaskExecuter.run(TaskExecuter.java:82)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-15 10:03:23:450 [pool-1-thread-1] ERROR  net.sourceforge.squirrel_sql.fw.util.TaskThreadPool  - Error
java.lang.IllegalStateException: Failed any way to execute content SQL. See former warning log entries for details.
        at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.table.ContentsTab.createDataSet(ContentsTab.java:255)
        at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.BaseDataSetTab.lambda$refreshComponent$0(BaseDataSetTab.java:127)
        at net.sourceforge.squirrel_sql.fw.util.TaskExecuter.run(TaskExecuter.java:82)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by gerdwagner** [comment]
You may try out the following:
Go to menu File --> Global Preferences --> tab "SQL Script" --> check "Use double quotes (") for qualifying".

If this doesn't solve your problem please check if it also exists in the latest snapshots. The latest snapshots can be found here
https://sourceforge.net/projects/squirrel-sql/files/3-snapshots
and here 
https://github.com/squirrel-sql-client/squirrel-sql-snapshot-releases/releases

**Comment by rgordill** [comment]
That does the trick. Thanks.
