### ISSUE TITLE
[MSSQL] SQLServerException on tab 'Content' or 'Row Count': Incorrect syntax (of auto-generated statement)

### ISSUE THREAD

**Issue by skipperTux** [squirrel-sql-client/squirrel-sql-code#37]
* SQuirreL SQL Client Version 4.7.1
* [Microsoft JDBC Driver for SQL Server 12.8.0](https://github.com/microsoft/mssql-jdbc/releases)
* java.vm.version 21.0.4+7
* java.runtime.version 21.0.4+7

I have tables named like `@My_TableName`, and this is a valid table name in MSSQL Server. However when clicking on _Objects->Content_ or _Objects->Row Count_ no result is shown and I get an exception, because the auto-generated syntax for the statement is wrong. The generated syntax is 
`select * from MY_DB.dbo.@My_TableName`, 
however it shall be 
`select * from MY_DB.dbo.[@My_TableName]` with the `@table` quoted in brackets.

It looks like a regression to me, as it used to work in older SQuirreL versions.

<details>
<summary>Content : SQLServerException</summary>

```
2024-08-01 17:58:40:582 [pool-1-thread-1] WARN  net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.table.ContentsTab  - Failed to execute content SQL: select * from MY_DB.dbo.@My_TableName tbl
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '@My_TableName'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:261)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1752)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:946)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:840)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7739)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4384)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:293)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:263)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:762)
	at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.table.ContentsTab.createResultSet(ContentsTab.java:352)
	at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.table.ContentsTab.createDataSet(ContentsTab.java:251)
	at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.BaseDataSetTab.lambda$refreshComponent$0(BaseDataSetTab.java:127)
	at net.sourceforge.squirrel_sql.fw.util.TaskExecuter.run(TaskExecuter.java:82)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
</details>

<details>
<summary>Row Count : SQLServerException</summary>

```
2024-08-01 19:00:18:859 [pool-1-thread-1] ERROR  net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.BaseDataSetTab  - <messageIsNull>
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '@My_TableName'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:270)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1778)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:946)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:840)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7775)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4408)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:293)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:263)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:762)
	at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.table.RowCountTab.createDataSet(RowCountTab.java:75)
	at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.BaseDataSetTab.lambda$refreshComponent$0(BaseDataSetTab.java:127)
	at net.sourceforge.squirrel_sql.fw.util.TaskExecuter.run(TaskExecuter.java:82)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
</details>

**Comment by gerdwagner** [comment]
Please try out this: Go to menu "Global Preferences" --> tab "SQL Scripts" --> check "Use double quotes for qualifying".

By the way double quotes are an alternative to square brackets.

**Comment by skipperTux** [comment]
I tried this before and it was already checked, but did not work. After I deleted the schema cache file and did a _Refresh Tree and Cache_ it worked, so that did the trick.
Thank you for your support. Case closed.
