### ISSUE TITLE
Reuse the "Cell value" dialog

### ISSUE THREAD

**Issue by fml2** [squirrel-sql-client/squirrel-sql-code#45]
This is a spin off of #41.

As of now, each double click on a cell (when browsing through the table contents, i.e. NOT the results of a SQL statement) produces a new "Cell value" dialog instance. If I want to quickly inspect several cells, I end up with many open dialogs (which are then cumbersome to close).

It would be nice if the dialog could be reused for displaying of cell values. I.e. if the dialog is already open, it gets reused for displaying a cell value on double click (without opening a new dialog instance).

But sometimes it's desireable to see two values at the same time, i.e. to have multiple instances of the dialog. This could be achieved by having a check box (or a "pin") in the dialog. If it's activated, the dialog gets reused when a cell is double clicked. If it's not activated, a new dialog is opened.

In the results of a SQL it's possible to display the same dialog which ist always reused. Hence the problem is not present there.

Thank you for the great program!

**Comment by gerdwagner** [comment]
The following was implemented and will be available in future snapshots and versions (excerpt from change log):

> https://github.com/squirrel-sql-client/squirrel-sql-code/issues/45
>   Table cell data popup dialog now offers a toggle button to pin the dialog.
>   When pinned any further cell data will be displayed in the pinned dialog.

**Comment by t603** [comment]
Hello, Gerd, I tried it on "squirrel-sql-snapshot-20241103_2144-standard.jar" just now and I guess it works as fml2 asked. By the way, this is a feature, we wanted asked too. So I am very glad, that fml2 asked it and You implemented it. Stepan

**Comment by fml2** [comment]
Implemented with 4b51d05d55e5de56128c36051a7c5b5c44221f88.

**Comment by fml2** [comment]
This weird, but I get an error when running the snapshot `20241103_2144` (which was created after implementing this feature request). I tried to remove all the plugins and still get the error. The previous snapshot `20241028_1950` is executed without any problems. I use OpenJDK 11.

The stack trace is:

```
java.lang.NullPointerException: Cannot invoke "net.sourceforge.squirrel_sql.fw.datasetviewer.cellcomponent.IDataTypeComponent.getHorizontalAlignmentOrNull()" because "this._dataTypeObject" is null
	at net.sourceforge.squirrel_sql.fw.datasetviewer.cellcomponent.CellRenderer.getTableCellRendererComponent(CellRenderer.java:41)
	at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5818)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2187)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2086)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1882)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:852)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at net.sourceforge.squirrel_sql.fw.datasetviewer.DataSetViewerTable.paint(DataSetViewerTable.java:84)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JSplitPane.paintChildren(JSplitPane.java:1034)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1656)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1631)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at net.sourceforge.squirrel_sql.client.Main$1.dispatchEvent(Main.java:101)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by gerdwagner** [comment]
The bug from the previous comment was fixed and will be available in future screenshots and versions.
Sorry for the inconvenience.

The change log entry for the bug is

> https://github.com/squirrel-sql-client/squirrel-sql-code/issues/45#issuecomment-2455169657
>   Fixed NullPointerException that occurred in some tables.

**Comment by fml2** [comment]
Now everything works well, thank you for the quick fix!

May I propose a couple of improvements (IMO)?

1. When the cell value dialog is pinned, it would be cool if it displayed the value of the cell under focus, i.e. without a double click. Like it's in the SQL results. This can be made optional (i.e. another check box), but it would be "featuritis" then.

2. The "pin" property could be persisted. This is a very minor issue though.

**Comment by fml2** [comment]
I've created #48 for this. This issue can be kept closed.
